<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FV7QQA3" failures="1" tests="1" name="testRunner.CheckTrackRunner" time="22.749" errors="0" timestamp="2023-12-21T16:19:19 IST" skipped="0">
  <testcase classname="testRunner.CheckTrackRunner" name="runScenario" time="22.749">
    <failure message="expected [Login Successfu] but found [Login Successful]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login Successfu] but found [Login Successful]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepDefination.CheckTrackLoginDef.varify_login_succefull(CheckTrackLoginDef.java:114)
at âœ½.varify login succefull(file:///C:/AkashWorkspace/WorkSpaceEclips/CucumberAuto/./FeatureFile/CheckTrackLogin.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.CheckTrackRunner -->
